language: scala
sudo: false
scala:
  - "2.13.0-RC1"
  - "2.12.8"
  - "2.11.12"
  - "2.10.7"
jdk:
  - openjdk8
  - openjdk11
script:
  - sbt ++${TRAVIS_SCALA_VERSION} test:compile checkScalariform
  - sbt ++${TRAVIS_SCALA_VERSION} test
matrix:
  exclude:
  - scala: 2.13.0-RC1
    jdk: openjdk11
  - scala: 2.11.12
    jdk: openjdk11
  - scala: 2.10.7
    jdk: openjdk11
